config/routes.rb
Rails.application.routes.draw do
  get 'doctor/hospital'
  get 'doctor/receptionist'
  get 'users/create'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/patient_record.rb
class PatientRecord < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :timeoutable, :registerable, :recoverable, :rememberable, :validatable, :authentication_keys => [:email]

  enum role: { receptionist: "receptionist", doctor: "doctor" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
  
    protected
  
    def after_sign_in_path_for(resource)
      if resource.receptionist?
        receptionist_path
      elsif resource.doctor?
        doctor_path
      else
        root_path
      end
    end
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :role])
    end
  end
  

app/controllers/doctor_controller.rb
class DoctorController < ApplicationController
  def index
      @patient_records = PatientRecord.all
  end

  def graph
      @registration_data = PatientRecord.group_by_day(:created_at, range: 1.week.ago..Time.now).count
  end
end

app/controllers/hospital_controller.rb
class HospitalController < ApplicationController
    def index
        @patient_records = PatientRecord.all
    end
end

app/controllers/receptionist_controller.rb
class ReceptionistController < ApplicationController

    def index
      @patient_records = PatientRecord.all
      @new_patient_record = PatientRecord.new
    end
  
  
      def new
          @new_patient_record = PatientRecord.new
      end
  
      def create
          @new_patient_record = PatientRecord.new(patient_params)
          if @new_patient_record.save
            redirect_to receptionist_path, notice: "Patient record created successfully."
          else
            render :new
          end
      end
  
      def show
        @patient_record = PatientRecord.find(params[:id])
      end
  
      def edit
        @patient_record = PatientRecord.find(params[:id])
      end
    
      def update
        @patient_record = PatientRecord.find(params[:id])
        if @patient_record.update(patient_params)
          redirect_to receptionist_path, notice: "Patient record updated successfully."
        else
          render :edit
        end
      end
  
      def destroy
        @patient_record = PatientRecord.find(params[:id])
        @patient_record.destroy
        redirect_to receptionist_path, notice: "Patient record deleted successfully."
      end
      
    
      private
    
      def patient_params
        params.require(:patient_record).permit(:name, :age)
      end
  
      def require_receptionist_role
        unless current_user.receptionist?
          redirect_to root_path, alert: "You don't have permission to access this page."
        end
      end
  end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    protected
  
    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/hospital_helper.rb
module HospitalHelper
end

app/helpers/receptionist_helper.rb
module ReceptionistHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/doctor/graph.html.erb
<h1>Patient vs Day Graph</h1>

<%= area_chart @registration_data %>

<%= link_to "Go back to main page", doctor_path %>

app/views/doctor/index.html.erb
<h1>Hospital ke Doctor Portal me aapka swagat hai🙏</h1>
<%= link_to "Check weekly graph", doctor_graph_path %>

<h3>List of all Patients</h3>
<% @patient_records.order(created_at: :asc).each do |patient| %>
    <div class="patient-data">
        <h6><%= patient.name %><h6>
        <p>Age:  <%= patient.age %> </p>
        <p>Admitted on:  <%= patient.created_at.strftime("%d %B %Y") %></p>
    </div>
<% end %>

<style>
    .patient-data{
        margin: 20px 10px;

        & h6{
            font-size: 20px;
            margin: 0;
        }

        & p{
            font-size: 15px;
            margin: 0;
        }
    }
</style>

app/views/hospital/index.html.erb
<h1>WelCome To Hosiptal Portal - Made By Lokesh</h1>



<%= link_to "Sign Up", "users/sign_in" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/receptionist/edit.html.erb
<h1>Edit patient record</h1>

<%= form_with model: @patient_record, url: update_patient_path(@patient_record), method: :patch do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <%= form.submit "Update Patient" %>
<% end %>

app/views/receptionist/index.html.erb
<h1>List of patients</h1>

<%= link_to "Add New Patient", new_patient_path %>


<% @patient_records.order(created_at: :asc).each do |patient| %>
  <div class="patient-data">
    <h6><%= patient.name %></h6>
    <p>Age <%= patient.age %></p>
    <%= link_to "Edit", edit_patient_path(patient) %>
    <%= link_to "Details", patient_details_path(patient) %>
    <%= button_to "Delete", delete_patient_path(patient), method: :delete, data: { confirm: "Are you sure you want to delete this patient?" } %> 
  </div> 
<% end %>



<style>
    .patient-data{
        margin: 20px 10px;

        & h6{
            font-size: 20px;
            margin: 0;
        }

        & p{
            font-size: 15px;
            margin: 0;
        }
    }
</style>

app/views/receptionist/new.html.erb
<h1>Add new patient</h1>

<%= form_with model: @new_patient_record, url: receptionist_create_path do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.label :age %>
        <%= form.text_field :age %>
    </div>

    <%= form.button %>
<% end %>

app/views/receptionist/show.html.erb
<h1>Patient Details</h1>

<div class="patient-data">
  <h3><%= @patient_record.name %></h3>
  <p>Age: <%= @patient_record.age %></p>
</div>

 <%= button_to "Delete Patient", delete_patient_path(@patient_record), method: :delete, data: { confirm: "Are you sure you want to delete this patient?" } %>
<%= link_to "Back to Patient List", receptionist_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>